# Generated by Django 6.0.3 on 2026-05-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='products/flowers/', verbose_name='Дополнительное изображение 1')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='products/flowers/', verbose_name='Дополнительное изображение 2')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='products/flowers/', verbose_name='Дополнительное изображение 3')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('width', models.FloatField(verbose_name='Ширина (см)')),
                ('length', models.FloatField(verbose_name='Длина (см)')),
                ('flowers', models.CharField(blank=True, choices=[('roses', 'Розы'), ('tulips', 'Тюльпаны'), ('peonies', 'Пионы'), ('lilies', 'Лилии'), ('daisies', 'Ромашки'), ('baskets', 'Корзины с цветами')], max_length=20, null=True, verbose_name='Цветы')),
                ('bouquets', models.CharField(blank=True, choices=[('classic', 'Классические'), ('original', 'Оригинальные'), ('edible', 'Съедобные'), ('wedding', 'Свадебные')], max_length=20, null=True, verbose_name='Букеты')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_info', models.CharField(max_length=100, verbose_name='Информация о дате')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('wishes', models.TextField(blank=True, verbose_name='Пожелания')),
                ('payment_method', models.CharField(choices=[('immediate', 'Оплата сразу'), ('upon_receipt', 'Оплата при получении')], max_length=15, verbose_name='Способ оплаты')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('collecting', 'Собираем'), ('shipped', 'Отправлен'), ('received', 'Получен'), ('cancelled', 'Отменен')], default='collecting', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.product', verbose_name='Товар')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile', verbose_name='Пользователь')),
            ],
        ),
    ]
